// Curated list of fun, weird, safe-for-work destinations.
// Each entry gets a stable id so votes survive even if the list is reordered.
module.exports = [
  { id: "zombo", url: "https://html5zombo.com/", label: "Zombocom" },
  { id: "useless-web", url: "https://theuselessweb.com/", label: "The Useless Web" },
  { id: "pointer-pointer", url: "https://pointerpointer.com/", label: "Pointer Pointer" },
  { id: "koalas-to-the-max", url: "https://www.koalastothemax.com/", label: "Koalas to the Max" },
  { id: "staggering-beauty", url: "http://www.staggeringbeauty.com/", label: "Staggering Beauty" },
  { id: "endless-horse", url: "https://endless.horse/", label: "Endless Horse" },
  { id: "corndog", url: "https://corndog.io/", label: "Corndog" },
  { id: "paper-toilet", url: "https://papertoilet.com/", label: "Paper Toilet" },
  { id: "radio-garden", url: "https://radio.garden/", label: "Radio Garden" },
  { id: "wikipedia-random", url: "https://en.wikipedia.org/wiki/Special:Random", label: "Random Wikipedia Page" },
  { id: "nyan-cat", url: "https://www.nyan.cat/", label: "Nyan Cat" },
  { id: "cat-bounce", url: "https://catbounce.com/", label: "Cat Bounce" },
  { id: "bouncy-balls", url: "https://bouncyballs.org/", label: "Bouncy Balls" },
  { id: "eel-slice", url: "https://eelslap.com/", label: "Eel Slap" },
  { id: "everysingle-photo", url: "https://everysingleframe.com/", label: "Everysingleframe" },
  { id: "one-red-paperclip", url: "https://en.wikipedia.org/wiki/One_red_paperclip", label: "One Red Paperclip" },
  { id: "hackertyper", url: "https://hackertyper.net/", label: "Hacker Typer" },
  { id: "trypap", url: "https://trypap.com/", label: "Pointless Sites Hub" },
  { id: "randomcolour", url: "https://www.colorhunt.co/palette/random", label: "Random Color Palette" },
  { id: "windows93", url: "https://www.windows93.net/", label: "Windows 93" },
  { id: "internet-archive", url: "https://archive.org/random", label: "Internet Archive Random Item" },
  { id: "weavesilk", url: "https://weavesilk.com/", label: "Weave Silk" },
  { id: "chaos-wheel", url: "https://www.wheelofnames.com/", label: "Wheel of Names" },
  { id: "geoguessr-explore", url: "https://www.geoguessr.com/free", label: "GeoGuessr Free Round" },
  { id: "window-swap", url: "https://www.window-swap.com/", label: "Window Swap" },
  { id: "boredbutton", url: "https://boredbutton.com/", label: "Bored Button" },
  { id: "thispersondoesnotexist", url: "https://this-person-does-not-exist.com/", label: "This Person Does Not Exist" },
  { id: "spacecat", url: "https://www.spacejam.com/1996/", label: "Original Space Jam Website" },
  { id: "cameroon", url: "https://cameronsworld.net/", label: "Cameron's World" },
  { id: "the-oatmeal", url: "https://theoatmeal.com/", label: "The Oatmeal" },
  { id: "google-doodles", url: "https://www.google.com/doodles", label: "Google Doodles Archive" },
  { id: "map-crunch", url: "https://mapcrunch.com/", label: "MapCrunch (Random Street View)" },
  { id: "listen-to-wikipedia", url: "https://listen.hatnote.com/", label: "Listen to Wikipedia" },
  { id: "internet-tv", url: "https://www.pentametron.com/", label: "Pentametron" },
  { id: "silk-fishing", url: "https://www.fishtanklive.com/", label: "Fish Tank Live" },
  { id: "quick-draw", url: "https://quickdraw.withgoogle.com/", label: "Google Quick, Draw!" },
  { id: "semantris", url: "https://research.google.com/semantris/", label: "Semantris Word Game" },
  { id: "art-of-fugue", url: "https://www.patatap.com/", label: "Patatap" },
  { id: "random-street-art", url: "https://randomstreetview.com/", label: "Random Street View" },
  { id: "internet-museum", url: "https://www.textfiles.com/", label: "The Textfiles.com Archive" },

  { id: "zoomquilt", url: "https://zoomquilt.org/", label: "Zoom Quilt" },
  { id: "falling-falling", url: "https://fallingfalling.com/", label: "Falling Falling" },
  { id: "i-has-a-bucket", url: "https://ihasabucket.com/", label: "I Has A Bucket" },
  { id: "do-nothing", url: "https://www.donothingfor2minutes.com/", label: "Do Nothing for 2 Minutes" },
  { id: "omfgdogs", url: "https://omfgdogs.com/", label: "OMFGDogs" },
  { id: "is-it-christmas", url: "https://isitchristmas.com/", label: "Is It Christmas?" },
  { id: "pixel-thoughts", url: "https://pixelthoughts.co/", label: "Pixel Thoughts" },
  { id: "neal-fun", url: "https://neal.fun/", label: "Neal.fun" },
  { id: "internet-machine", url: "https://neal.fun/internet-machine/", label: "The Internet Machine" },
  { id: "trolley-problems", url: "https://neal.fun/absurd-trolley-problems/", label: "Absurd Trolley Problems" },
  { id: "password-game", url: "https://neal.fun/password-game/", label: "The Password Game" },
  { id: "infinite-craft", url: "https://neal.fun/infinite-craft/", label: "Infinite Craft" },
  { id: "asteroid-launcher", url: "https://neal.fun/asteroid-launcher/", label: "Asteroid Launcher" },
  { id: "cookie-clicker", url: "https://orteil.dashnet.org/cookieclicker/", label: "Cookie Clicker" },
  { id: "minesweeper-online", url: "https://minesweeper.online/", label: "Minesweeper Online" },
  { id: "play-2048", url: "https://play2048.co/", label: "2048" },
  { id: "akinator", url: "https://en.akinator.com/", label: "Akinator" },
  { id: "slow-roads", url: "https://slowroads.io/", label: "Slow Roads" },
  { id: "ciechanowski", url: "https://ciechanow.ski/", label: "Ciechanowski Explainables" },
  { id: "the-pudding", url: "https://pudding.cool/", label: "The Pudding" },
  { id: "scale-of-universe", url: "https://htwins.net/scale2/", label: "Scale of the Universe" },
  { id: "submarine-cable-map", url: "https://submarinecablemap.com/", label: "Submarine Cable Map" },
  { id: "worldometers", url: "https://www.worldometers.info/", label: "Worldometer" },
  { id: "spot-the-station", url: "https://spotthestation.nasa.gov/", label: "Spot the Station (NASA)" },
  { id: "nasa-eyes", url: "https://eyes.nasa.gov/", label: "NASA Eyes" },
  { id: "chrome-music-lab", url: "https://musiclab.chromeexperiments.com/", label: "Chrome Music Lab" },
  { id: "shadertoy", url: "https://www.shadertoy.com/", label: "Shadertoy" },
  { id: "open-processing", url: "https://openprocessing.org/", label: "OpenProcessing" },
  { id: "random-org", url: "https://www.random.org/", label: "Random.org" },
  { id: "random-dog", url: "https://random.dog/", label: "Random Dog" },
  { id: "random-fox", url: "https://randomfox.ca/", label: "Random Fox" },
  { id: "this-cat", url: "https://thiscatdoesnotexist.com/", label: "This Cat Does Not Exist" },
  { id: "this-artwork", url: "https://thisartworkdoesnotexist.com/", label: "This Artwork Does Not Exist" },
  { id: "this-horse", url: "https://thishorsedoesnotexist.com/", label: "This Horse Does Not Exist" },
  { id: "cursor-effects", url: "https://tholman.com/cursor-effects/", label: "Cursor Effects Gallery" },
  { id: "elastic-checkbox", url: "https://tholman.com/elastic-checkbox/", label: "Elastic Checkbox" },
  { id: "typeracer", url: "https://play.typeracer.com/", label: "TypeRacer" },
  { id: "keybr", url: "https://www.keybr.com/", label: "Keybr" },
  { id: "little-alchemy-2", url: "https://littlealchemy2.com/", label: "Little Alchemy 2" },
  { id: "draw-a-stickman", url: "https://drawastickman.com/", label: "Draw a Stickman" },
  { id: "slither-io", url: "https://slither.io/", label: "Slither.io" },
  { id: "agar-io", url: "https://agar.io/", label: "Agar.io" },
  { id: "krunker", url: "https://krunker.io/", label: "Krunker" },
  { id: "diep-io", url: "https://diep.io/", label: "Diep.io" },
  { id: "explore-org", url: "https://explore.org/livecams", label: "Explore.org Live Cams" },
  { id: "earthcam", url: "https://www.earthcam.com/", label: "EarthCam" },
  { id: "flightradar24", url: "https://www.flightradar24.com/", label: "Flightradar24" },
  { id: "ai-weirdness", url: "https://www.aiweirdness.com/", label: "AI Weirdness" },
  { id: "kottke", url: "https://kottke.org/", label: "Kottke.org" },
  { id: "atlas-obscura", url: "https://www.atlasobscura.com/", label: "Atlas Obscura" },
  { id: "open-culture", url: "https://www.openculture.com/", label: "Open Culture" },
  { id: "project-gutenberg", url: "https://www.gutenberg.org/", label: "Project Gutenberg" },
  { id: "windy", url: "https://www.windy.com/", label: "Windy.com" },
  { id: "marine-traffic", url: "https://www.marinetraffic.com/", label: "MarineTraffic" },
  { id: "webcam-taxi", url: "https://www.webcamtaxi.com/", label: "Webcam Taxi" },
  { id: "space-weather-live", url: "https://www.spaceweatherlive.com/", label: "Space Weather Live" },
  { id: "stellarium-web", url: "https://stellarium-web.org/", label: "Stellarium Web" },
  { id: "this-is-why-im-broke", url: "https://www.thisiswhyimbroke.com/", label: "This Is Why I'm Broke" },
  { id: "uncrate", url: "https://uncrate.com/", label: "Uncrate" },
  { id: "my-modern-met", url: "https://mymodernmet.com/", label: "My Modern Met" },
  { id: "colossal", url: "https://www.thisiscolossal.com/", label: "Colossal" },
  { id: "dribbble", url: "https://dribbble.com/", label: "Dribbble" },
  { id: "behance", url: "https://www.behance.net/", label: "Behance" },
  { id: "codepen-trending", url: "https://codepen.io/trending", label: "CodePen Trending" },
  { id: "glitch", url: "https://glitch.com/", label: "Glitch" },
  { id: "p5js-examples", url: "https://p5js.org/examples/", label: "p5.js Examples" },
  { id: "mapchart", url: "https://www.mapchart.net/", label: "MapChart" },
  { id: "globle-game", url: "https://globle-game.com/", label: "Globle" },
  { id: "contexto", url: "https://contexto.me/", label: "Contexto" },
  { id: "semantle", url: "https://semantle.com/", label: "Semantle" },
  { id: "gartic-io", url: "https://gartic.io/", label: "Gartic.io" },
  { id: "skribbl-io", url: "https://skribbl.io/", label: "Skribbl.io" },
  { id: "jklm-fun", url: "https://jklm.fun/", label: "JKLM.fun Party Games" },
  { id: "cleverbot", url: "https://www.cleverbot.com/", label: "Cleverbot" },
  { id: "elizabot", url: "https://www.masswerk.at/elizabot/", label: "ELIZA the Chatbot" },
  { id: "downforeveryoneorjustme", url: "https://downforeveryoneorjustme.com/", label: "Down For Everyone Or Just Me" },
  { id: "archillect", url: "https://archillect.com/", label: "Archillect" },
  { id: "bored-panda", url: "https://www.boredpanda.com/", label: "Bored Panda" },
  { id: "mental-floss", url: "https://www.mentalfloss.com/", label: "Mental Floss" },
  { id: "damn-you-autocorrect", url: "https://www.damnyouautocorrect.com/", label: "Damn You Autocorrect" },
  { id: "cheezburger", url: "https://cheezburger.com/", label: "I Can Has Cheezburger" },
  { id: "failblog", url: "https://failblog.cheezburger.com/", label: "FAIL Blog" },
  { id: "know-your-meme", url: "https://knowyourmeme.com/", label: "Know Your Meme" },
  { id: "tv-tropes", url: "https://tvtropes.org/", label: "TV Tropes" },
  { id: "uncyclopedia", url: "https://uncyclopedia.com/", label: "Uncyclopedia" },
  { id: "esolangs", url: "https://esolangs.org/", label: "Esolang Wiki" },
  { id: "explain-xkcd", url: "https://www.explainxkcd.com/", label: "Explain XKCD" },
  { id: "xkcd", url: "https://xkcd.com/", label: "xkcd" },
  { id: "xkcd-random", url: "https://c.xkcd.com/random/comic/", label: "Random xkcd" },
  { id: "smbc-comics", url: "https://www.smbc-comics.com/", label: "Saturday Morning Breakfast Cereal" },
  { id: "qwantz", url: "https://www.qwantz.com/", label: "Dinosaur Comics" },
  { id: "questionable-content", url: "https://www.questionablecontent.net/", label: "Questionable Content" },
  { id: "gunshow-comic", url: "https://gunshowcomic.com/", label: "Gunshow" },
  { id: "wait-but-why", url: "https://waitbutwhy.com/", label: "Wait But Why" },
  { id: "the-oatmeal-comics", url: "https://theoatmeal.com/comics", label: "The Oatmeal Comics" },
  { id: "penny-arcade", url: "https://www.penny-arcade.com/comic", label: "Penny Arcade" },
  { id: "achewood", url: "https://achewood.com/", label: "Achewood" },
  { id: "wondermark", url: "https://wondermark.com/", label: "Wondermark" },
  { id: "toothpaste-for-dinner", url: "https://www.toothpastefordinner.com/", label: "Toothpaste For Dinner" },
  { id: "cyanide-happiness", url: "https://explosm.net/", label: "Cyanide & Happiness" },
  { id: "buttersafe", url: "https://buttersafe.com/", label: "Buttersafe" },
];
